language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  webhooks:
    urls:
      - http://discord.pluginwiki.us/travis.php
    on_success: always
    on_failure: always
    on_start: always
before_deploy:
  - bash ./build.sh
before_install: "bash fetch_dependencies.sh"
script: "mvn -B package"
deploy:
  provider: releases
  api_key: ${TOKEN}
  file: "target/SimpleGadgets-*.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master
branches:
  except:
    - /^*-v[0-9]/