language: java
jdk:
  - oraclejdk8
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name ${GIT_NAME}
  - git config --local user.email ${GIT_EMAIL}
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: ${TOKEN}
  file: ".release/SimpleGadgets.jar"
  skip_cleanup: true
  on:
    branch: master