language: java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - http://discord.pluginwiki.us/travis.php
    on_success: always
    on_failure: always
    on_start: always
before_deploy:
  - bash ./build.sh
deploy:
  provider: releases
  api_key: ${TOKEN}
  file: ".release/SimpleGadgets.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master
branches:
  except:
    - /^*-v[0-9]/