name: SimpleGadgets
main: gadgets.brainsynder.Core
version: 1.5-SNAPSHOT
depends: [SimpleAPI]
loadbefore: [SimpleGadgets-Addon]
authors: [brainsynder]
commands:
  gadgets:
    description: Opens the gadgets menu.
    aliases: [gadget, simplegadgets, simplegadget]
  simplegadgets:
    description: Main SimpleGadgets commands.
    aliases: [simplegadget]